name: Misc
description: |
  Generic template for anything that doesn't fit elsewhere.
labels: [suggestion]
body:
  - type: markdown
    attributes:
      value: |
        Please use a concise and distinct title for the issue.

        Consider: Could you nerdsnipe someone upstream instead?        
  - type: textarea
    attributes:
      label: Pitch or whatever
      description: Describe your thought. If it has already been suggested/implemented/turned down before, please link to where.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Motivation
      description: Why do you think this feature is needed? Who would benefit from it?
    validations:
      required: false
